name: ts-lint
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
        
